### ISSUE TITLE
Prediction

### ISSUE THREAD

**Issue by psolymos** [psolymos/bamanalytics#2]
- [ ] make it run on WG
- [ ] predict current (a base year TBD)
- [ ] predict reference: all athropogenic disturbances are 0-ed out (not fire)
- [ ] land cover classes agr and disturbed: random non-disturbed in bootstrap (separate for each BCR/prov region unit)

**Comment by psolymos** [comment]
Land cover imputation: 0 out unwanted anthropogenic disturbances but keep **all** other (including years since fire etc) to get a random sample on each run.

Do partial backfill for the following sectors:
- agriculture (lcc=agr)
- forestry (forest loss)
- transportation/linear (Pasher lin)
- urban/industrial (lcc=devel, Pasher polygonal)

For base year, consider these:
- forest loss coverage (2002-12 -- want later?)
- year of other layers

'Backfilled' is an assumption, not a different year. Set YSF same as for 2012 base year.

**Comment by psolymos** [comment]
3 types of 'trend' we can look at:
1. residual trend (2002-2012),
2. habitat supply based trend (2002-2012),
3. 'sector effects' based on backfilled/reference and 2012 (current).

**Comment by psolymos** [comment]
## The types of results we need for each species

### Habitat associations and roadside effects

These figures are either based on (1) lower stage coefficients, or (2) marginal plots. Make both and decide later.
- [x] Habitat classes: marginal is better for forest stands. (coef based, marginal)
- [x] Forest-height relationships (coef based, marginal)
- [x] Roadside coefficient estimates (contrasts), ~~and marginal on/off road plot~~

### Disturbance, CTI and slope

These figures are either based on (1) lower stage coefficients, or (2) marginal plots. Make both and decide later. We also need to present model selection frequencies (e.g. continuous vs discrete, fire vs loss).
- [x] plot years-since relationships based on ~~coefficients and~~ marginal
- [x] present model selection freq in table (this might be for all stages) + coeficient summaries (SE etc)
- [x] plot CTI/slope relationships based on ~~coefficients and~~ marginal

### Climate

This is more relevant for prediction, but model selection frequencies as part of overall table is useful.

### Year effect and residual trend
- [x] Present histogram and quantiles of annual change.
- [ ] Present residual trend (all study area and BCR/prov units):
  - BAM
  - BBS
  - BAM+BBS combined

### Density map and summaries
- [x] predict under current (2012) conditions for the study area
- [x] predict under 2002 conditions for the study area and compare to 2012
- [x] predict under backfilled conditions (all sectors backfilled) and compare to 2012
- [ ] ~~predict under partially backfilled conditions (all sectors but one focal one) and compare to 2012~~

The following sectors can be distinguished:
1. Forestry (loss is set to a big years-since value, but not fire)
2. Transportation (LIN disturbance effects set to 0)
3. Urban-Industrial (incl energy): Urban (NALC imputed) and POL disturbance set to 0
4. Argiculture (NALC imputed)

> **NOTE**: GFW loss info includes not only forestry, so not clear how to separate sectors. Solution: drop this for now.
- [x] SD map for current (2012) conditions.
- [ ] BCR/prov type summaries of pop sizes (mean, median, PI).

### Goodness of fit
- [ ] Goodness of fit stats/plots.

### TODO
- [x] BRC/jurisdiction units for residual trend -- compare with BBS
- [x] BRC/jurisdiction units for population size -- compare with PIF
- [x] Species to consider for preliminary runs: RUBL, CAWA, OSFL, OVEN, CONI, MOWA

**Comment by psolymos** [comment]
Technical issues related to scaling up analyses:
- [x] randomly resample single within year revisit (i.e. not using only one), use code from AB CAWA script
- [ ] ~~use xlat/xlon for further constraining distribution where overprediction occurs (YEWA and RUBL, some extent CONW, OSFL, WETA)~~
- [x] check if large HGT values are causing extreme overprediction, and consider using discrete HGT categories to avoid overprediction, or simply truncate each B run pred separately (and not globally)
- [ ] Next things is to run only limited data and 1 (or few) bootstrap runs to identify the best way to minimize overprediction.
- [ ] Remove LIN and POL (Pasher et al BEAD layer) because those do not extend into the west (BC, YT) and US.
